version: "3.8"
services:
  jupyterlab:
    build: .
    platform: linux/x86_64
    container_name: docker-python
    volumes:
      - '.:/workspace'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
